- name: install dependent packages
  sudo: true
  apt: >
    name={{item}}
    state=present
  with_items:
    - python3-pip
    - python3-dev
    - lzop
    - pv
    - daemontools

- name: clone wal-e tool
  sudo: true
  git: >
    repo={{pg_wale_repo}}
    dest=/tmp/wal-e
    version={{pg_wale_version}}
    force=yes
    accept_hostkey=yes

- name: install wal-e
  become_user: "{{pg_wale_user}}"
  command: pip3 install boto boto3 wal-e

- name: create env directory
  sudo: true
  file: >
    state=directory
    owner={{pg_wale_user}}
    group={{pg_wale_user}}
    path={{pg_wale_env_folder}}

#---------------------------------------------------------

- name: create env file for AWS_SECRET_ACCESS_KEY
  sudo: true
  template: >
    src=AWS_SECRET_ACCESS_KEY.j2
    dest={{pg_wale_env_folder}}/AWS_SECRET_ACCESS_KEY
    owner={{pg_wale_user}}
    group={{pg_wale_user}}
    mode=640

- name: create env file for AWS_ACCESS_KEY_ID
  sudo: true
  template: >
    src=AWS_ACCESS_KEY_ID.j2
    dest={{pg_wale_env_folder}}/AWS_ACCESS_KEY_ID
    owner={{pg_wale_user}}
    group={{pg_wale_user}}
    mode=640

- name: create env file for AWS_REGION
  sudo: true
  template: >
    src=AWS_REGION.j2
    dest={{pg_wale_env_folder}}/AWS_REGION
    owner={{pg_wale_user}}
    group={{pg_wale_user}}
    mode=640

- name: create env file for WALE_S3_PREFIX
  sudo: true
  template: >
    src=WALE_S3_PREFIX.j2
    dest={{pg_wale_env_folder}}/WALE_S3_PREFIX
    owner={{pg_wale_user}}
    group={{pg_wale_user}}
    mode=640
